# Generated by Django 3.1 on 2020-11-13 08:26

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/category/%name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('weight', models.IntegerField()),
                ('dimension', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('model_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='images/product/%id')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/product/%id')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/product/%id')),
                ('category', models.ForeignKey(default='No Category', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Detalis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('has_Guaranty', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_Date', models.DateTimeField()),
                ('end_Date', models.DateTimeField()),
                ('percentage', models.IntegerField()),
                ('product_Details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product_detalis')),
            ],
        ),
    ]
