# Generated by Django 3.1 on 2020-12-04 10:42

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201129_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=shop.models.get_upload_path)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='long_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_name',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='fffffffffffffffff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='No Brand', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.brand'),
        ),
    ]
