# Generated by Django 3.1 on 2020-12-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201204_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_sold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
