# Generated by Django 3.1 on 2020-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_number_of_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_of_sold',
            field=models.IntegerField(default=0),
        ),
    ]
