# Generated by Django 3.1.4 on 2020-12-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201215_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(max_length=300),
        ),
    ]
